import Black from "./static/icons/black.png";
import Blue from "./static/icons/blue.png";
import White from "./static/icons/white.png";
import Red from "./static/icons/red.png";
import Alloy1 from "./static/icons/Alloy1.jpg";
import Alloy2 from "./static/icons/Alloy2.jpg";
import Alloy3 from "./static/icons/Alloy3.jpg";
import Hotspot from "./static/icons/HotspotIcon.png";
import WheelIcon from "./static/icons/WheelIcon.png";
import ColorIcon from "./static/icons/ColorIcon.png";
import {
  Scene1BaseImage,
  Scene1Category1Swatch1,
  Scene1Category1Swatch2,
  Scene1Category1Swatch3,
  Scene1Category1Swatch4,
  Scene1Category2Swatch1,
  Scene1Category2Swatch2,
  Scene1Category2Swatch3,
} from "./static/Scene-1";
import {
  Scene6BaseImage,
  Scene6Category1Swatch1,
  Scene6Category1Swatch2,
  Scene6Category1Swatch3,
  Scene6Category1Swatch4,
  Scene6Category2Swatch1,
  Scene6Category2Swatch2,
  Scene6Category2Swatch3,
} from "./static/Scene-6";
import {
  Scene2BaseImage,
  Scene2Category1Swatch1,
  Scene2Category1Swatch2,
  Scene2Category1Swatch3,
  Scene2Category1Swatch4,
} from "./static/Scene-2";
import {
  Scene7BaseImage,
  Scene7Category1Swatch1,
  Scene7Category1Swatch2,
  Scene7Category1Swatch3,
  Scene7Category1Swatch4,
} from "./static/Scene-7";
import {
  Scene3BaseImage,
  Scene3Category1Swatch1,
  Scene3Category1Swatch2,
  Scene3Category1Swatch3,
  Scene3Category1Swatch4,
  Scene3Category2Swatch1,
  Scene3Category2Swatch2,
  Scene3Category2Swatch3,
} from "./static/Scene-3";
import {
  Scene8BaseImage,
  Scene8Category1Swatch1,
  Scene8Category1Swatch2,
  Scene8Category1Swatch3,
  Scene8Category1Swatch4,
  Scene8Category2Swatch1,
  Scene8Category2Swatch2,
  Scene8Category2Swatch3,
} from "./static/Scene-8";
import {
  Scene4BaseImage,
  Scene4Category1Swatch1,
  Scene4Category1Swatch2,
  Scene4Category1Swatch3,
  Scene4Category1Swatch4,
  Scene4Category2Swatch1,
  Scene4Category2Swatch2,
  Scene4Category2Swatch3,
} from "./static/Scene-4";
import {
  Scene9BaseImage,
  Scene9Category1Swatch1,
  Scene9Category1Swatch2,
  Scene9Category1Swatch3,
  Scene9Category1Swatch4,
  Scene9Category2Swatch1,
  Scene9Category2Swatch2,
  Scene9Category2Swatch3,
} from "./static/Scene-9";
import {
  Scene5BaseImage,
  Scene5Category1Swatch1,
  Scene5Category1Swatch2,
  Scene5Category1Swatch3,
  Scene5Category1Swatch4,
} from "./static/Scene-5";
import {
  Scene10BaseImage,
  Scene10Category1Swatch1,
  Scene10Category1Swatch2,
  Scene10Category1Swatch3,
  Scene10Category1Swatch4,
} from "./static/Scene-10";

export const DATA: IVisualizer = {
  name: "Bugati",
  id: 2691,
  scenes: [
    {
      id: 4801,
      name: "Closed_Door_Side",
      baseImage: Scene1BaseImage,
      initialPosition: { x: 0, y: 0, z: 0 },
      initialRotation: { x: 0, y: -90, z: 0 },
      isDefault: true,
      categories: [
        {
          id: 3801,
          name: "Color",
          thumbnail: ColorIcon,
          swatches: [
            {
              id: 2801,
              name: "Black",
              isSelected: true,
              path: Scene1Category1Swatch1,
              thumbnailPath: Black,
              initialPosition: { x: 0, y: 0, z: 0 },
              initialRotation: { x: 0, y: -90, z: 0 },
            },
            {
              id: 2802,
              name: "Blue",
              isSelected: false,
              path: Scene1Category1Swatch2,
              thumbnailPath: Blue,
              initialPosition: { x: 0, y: 0, z: 0 },
              initialRotation: { x: 0, y: -90, z: 0 },
            },
            {
              id: 2803,
              name: "Red",
              isSelected: false,
              path: Scene1Category1Swatch3,
              thumbnailPath: Red,
              initialPosition: { x: 0, y: 0, z: 0 },
              initialRotation: { x: 0, y: -90, z: 0 },
            },
            {
              id: 2804,
              name: "White",
              isSelected: false,
              path: Scene1Category1Swatch4,
              thumbnailPath: White,
              initialPosition: { x: 0, y: 0, z: 0 },
              initialRotation: { x: 0, y: -90, z: 0 },
            },
          ],
        },
        {
          id: 3802,
          name: "Alloys",
          thumbnail: WheelIcon,
          swatches: [
            {
              id: 2805,
              name: "Alloy 1",
              isSelected: true,
              path: Scene1Category2Swatch1,
              thumbnailPath: Alloy1,
              initialPosition: { x: 0, y: 0, z: 0 },
              initialRotation: { x: 0, y: -90, z: 0 },
            },
            {
              id: 2806,
              name: "Alloy 2",
              isSelected: false,
              path: Scene1Category2Swatch2,
              thumbnailPath: Alloy2,
              initialPosition: { x: 0, y: 0, z: 0 },
              initialRotation: { x: 0, y: -90, z: 0 },
            },
            {
              id: 2807,
              name: "Alloy 3",
              isSelected: false,
              path: Scene1Category2Swatch3,
              thumbnailPath: Alloy3,
              initialPosition: { x: 0, y: 0, z: 0 },
              initialRotation: { x: 0, y: -90, z: 0 },
            },
          ],
        },
      ],
      hotspots: [
        {
          id: 1801,
          thumbnail: Hotspot,
          header: "Scene 2",
          sceneId: 4802,
          initialPosition: { x: 10, y: 0, z: -15 },
          initialRotation: { x: 0, y: 0, z: 0 },
        },
        {
          id: 1802,
          thumbnail: Hotspot,
          header: "Scene 3",
          sceneId: 4803,
          initialPosition: { x: 17, y: -6, z: -15 },
          initialRotation: { x: 0, y: 0, z: 0 },
        },
        {
          id: 1803,
          thumbnail: Hotspot,
          header: "Scene 4",
          sceneId: 4804,
          initialPosition: { x: -14, y: -6, z: -15 },
          initialRotation: { x: 0, y: 0, z: 0 },
        },
        {
          id: 1804,
          thumbnail: Hotspot,
          header: "Scene 5",
          sceneId: 4805,
          initialPosition: { x: -14, y: -1, z: -15 },
          initialRotation: { x: 0, y: 0, z: 0 },
        },
      ],
    },
    {
      id: 4802,
      name: "Closed_Door_Front",
      baseImage: Scene2BaseImage,
      initialPosition: { x: 0, y: 0, z: 0 },
      initialRotation: { x: 0, y: -90, z: 0 },
      isDefault: false,
      categories: [
        {
          id: 3801,
          name: "Color",
          thumbnail: ColorIcon,
          swatches: [
            {
              id: 2801,
              name: "Black",
              isSelected: true,
              path: Scene2Category1Swatch1,
              thumbnailPath: Black,
              initialPosition: { x: 0, y: 0, z: 0 },
              initialRotation: { x: 0, y: -90, z: 0 },
            },
            {
              id: 2802,
              name: "Blue",
              isSelected: false,
              path: Scene2Category1Swatch2,
              thumbnailPath: Blue,
              initialPosition: { x: 0, y: 0, z: 0 },
              initialRotation: { x: 0, y: -90, z: 0 },
            },
            {
              id: 2803,
              name: "Red",
              isSelected: false,
              path: Scene2Category1Swatch3,
              thumbnailPath: Red,
              initialPosition: { x: 0, y: 0, z: 0 },
              initialRotation: { x: 0, y: -90, z: 0 },
            },
            {
              id: 2804,
              name: "White",
              isSelected: false,
              path: Scene2Category1Swatch4,
              thumbnailPath: White,
              initialPosition: { x: 0, y: 0, z: 0 },
              initialRotation: { x: 0, y: -90, z: 0 },
            },
          ],
        },
      ],
      hotspots: [
        {
          id: 1805,
          thumbnail: Hotspot,
          header: "Scene 1",
          sceneId: 4801,
          initialPosition: { x: -4, y: -1, z: -15 },
          initialRotation: { x: 0, y: 0, z: 0 },
        },
        {
          id: 1806,
          thumbnail: Hotspot,
          header: "Scene 3",
          sceneId: 4803,
          initialPosition: { x: -5, y: -8, z: -15 },
          initialRotation: { x: 0, y: 0, z: 0 },
        },
        {
          id: 1807,
          thumbnail: Hotspot,
          header: "Scene 4",
          sceneId: 4804,
          initialPosition: { x: 4, y: 0, z: -15 },
          initialRotation: { x: 0, y: 0, z: 0 },
        },
        {
          id: 1808,
          thumbnail: Hotspot,
          header: "Scene 5",
          sceneId: 4805,
          initialPosition: { x: 0.5, y: 1, z: -15 },
          initialRotation: { x: 0, y: 0, z: 0 },
        },
      ],
    },
    {
      id: 4803,
      name: "Closed_Door_Right",
      baseImage: Scene3BaseImage,
      initialPosition: { x: 0, y: 0, z: 0 },
      initialRotation: { x: 0, y: -90, z: 0 },
      isDefault: false,
      categories: [
        {
          id: 3801,
          name: "Color",
          thumbnail: ColorIcon,
          swatches: [
            {
              id: 2801,
              name: "Black",
              isSelected: true,
              path: Scene3Category1Swatch1,
              thumbnailPath: Black,
              initialPosition: { x: 0, y: 0, z: 0 },
              initialRotation: { x: 0, y: -90, z: 0 },
            },
            {
              id: 2802,
              name: "Blue",
              isSelected: false,
              path: Scene3Category1Swatch2,
              thumbnailPath: Blue,
              initialPosition: { x: 0, y: 0, z: 0 },
              initialRotation: { x: 0, y: -90, z: 0 },
            },
            {
              id: 2803,
              name: "Red",
              isSelected: false,
              path: Scene3Category1Swatch3,
              thumbnailPath: Red,
              initialPosition: { x: 0, y: 0, z: 0 },
              initialRotation: { x: 0, y: -90, z: 0 },
            },
            {
              id: 2804,
              name: "White",
              isSelected: false,
              path: Scene3Category1Swatch4,
              thumbnailPath: White,
              initialPosition: { x: 0, y: 0, z: 0 },
              initialRotation: { x: 0, y: -90, z: 0 },
            },
          ],
        },
        {
          id: 3802,
          name: "Alloys",
          thumbnail: WheelIcon,
          swatches: [
            {
              id: 2805,
              name: "Alloy 1",
              isSelected: true,
              path: Scene3Category2Swatch1,
              thumbnailPath: Alloy1,
              initialPosition: { x: 0, y: 0, z: 0 },
              initialRotation: { x: 0, y: -90, z: 0 },
            },
            {
              id: 2806,
              name: "Alloy 2",
              isSelected: false,
              path: Scene3Category2Swatch2,
              thumbnailPath: Alloy2,
              initialPosition: { x: 0, y: 0, z: 0 },
              initialRotation: { x: 0, y: -90, z: 0 },
            },
            {
              id: 2807,
              name: "Alloy 3",
              isSelected: false,
              path: Scene3Category2Swatch3,
              thumbnailPath: Alloy3,
              initialPosition: { x: 0, y: 0, z: 0 },
              initialRotation: { x: 0, y: -90, z: 0 },
            },
          ],
        },
      ],
      hotspots: [
        {
          id: 1809,
          thumbnail: Hotspot,
          header: "Scene 1",
          sceneId: 4801,
          initialPosition: { x: -8, y: -4, z: -15 },
          initialRotation: { x: 0, y: 0, z: 0 },
        },
        {
          id: 1810,
          thumbnail: Hotspot,
          header: "Scene 2",
          sceneId: 4802,
          initialPosition: { x: 4, y: -4, z: -15 },
          initialRotation: { x: 0, y: 0, z: 0 },
        },
        {
          id: 1811,
          thumbnail: Hotspot,
          header: "Scene 4",
          sceneId: 4804,
          initialPosition: { x: -10, y: -4, z: -15 },
          initialRotation: { x: 0, y: 0, z: 0 },
        },
        {
          id: 1812,
          thumbnail: Hotspot,
          header: "Scene 5",
          sceneId: 4805,
          initialPosition: { x: -8, y: 1, z: -15 },
          initialRotation: { x: 0, y: 0, z: 0 },
        },
      ],
    },
    {
      id: 4804,
      name: "Closed_Door_Left",
      baseImage: Scene4BaseImage,
      initialPosition: { x: 0, y: 0, z: 0 },
      initialRotation: { x: 0, y: -90, z: 0 },
      isDefault: false,
      categories: [
        {
          id: 3801,
          name: "Color",
          thumbnail: ColorIcon,
          swatches: [
            {
              id: 2801,
              name: "Black",
              isSelected: true,
              path: Scene4Category1Swatch1,
              thumbnailPath: Black,
              initialPosition: { x: 0, y: 0, z: 0 },
              initialRotation: { x: 0, y: -90, z: 0 },
            },
            {
              id: 2802,
              name: "Blue",
              isSelected: false,
              path: Scene4Category1Swatch2,
              thumbnailPath: Blue,
              initialPosition: { x: 0, y: 0, z: 0 },
              initialRotation: { x: 0, y: -90, z: 0 },
            },
            {
              id: 2803,
              name: "Red",
              isSelected: false,
              path: Scene4Category1Swatch3,
              thumbnailPath: Red,
              initialPosition: { x: 0, y: 0, z: 0 },
              initialRotation: { x: 0, y: -90, z: 0 },
            },
            {
              id: 2804,
              name: "White",
              isSelected: false,
              path: Scene4Category1Swatch4,
              thumbnailPath: White,
              initialPosition: { x: 0, y: 0, z: 0 },
              initialRotation: { x: 0, y: -90, z: 0 },
            },
          ],
        },
        {
          id: 3802,
          name: "Alloys",
          thumbnail: WheelIcon,
          swatches: [
            {
              id: 2805,
              name: "Alloy 1",
              isSelected: true,
              path: Scene4Category2Swatch1,
              thumbnailPath: Alloy1,
              initialPosition: { x: 0, y: 0, z: 0 },
              initialRotation: { x: 0, y: -90, z: 0 },
            },
            {
              id: 2806,
              name: "Alloy 2",
              isSelected: false,
              path: Scene4Category2Swatch2,
              thumbnailPath: Alloy2,
              initialPosition: { x: 0, y: 0, z: 0 },
              initialRotation: { x: 0, y: -90, z: 0 },
            },
            {
              id: 2807,
              name: "Alloy 3",
              isSelected: false,
              path: Scene4Category2Swatch3,
              thumbnailPath: Alloy3,
              initialPosition: { x: 0, y: 0, z: 0 },
              initialRotation: { x: 0, y: -90, z: 0 },
            },
          ],
        },
      ],
      hotspots: [
        {
          id: 1813,
          thumbnail: Hotspot,
          header: "Scene 1",
          sceneId: 4801,
          initialPosition: { x: 9, y: -4, z: -15 },
          initialRotation: { x: 0, y: 0, z: 0 },
        },
        {
          id: 1814,
          thumbnail: Hotspot,
          header: "Scene 2",
          sceneId: 4802,
          initialPosition: { x: 10, y: 0, z: -15 },
          initialRotation: { x: 0, y: 0, z: 0 },
        },
        {
          id: 1815,
          thumbnail: Hotspot,
          header: "Scene 3",
          sceneId: 4803,
          initialPosition: { x: 11, y: -3, z: -15 },
          initialRotation: { x: 0, y: 0, z: 0 },
        },
        {
          id: 1816,
          thumbnail: Hotspot,
          header: "Scene 5",
          sceneId: 4805,
          initialPosition: { x: -1, y: -5, z: -15 },
          initialRotation: { x: 0, y: 0, z: 0 },
        },
      ],
    },
    {
      id: 4805,
      name: "Closed_Door_Back",
      baseImage: Scene5BaseImage,
      initialPosition: { x: 0, y: 0, z: 0 },
      initialRotation: { x: 0, y: -90, z: 0 },
      isDefault: false,
      categories: [
        {
          id: 3801,
          name: "Color",
          thumbnail: ColorIcon,
          swatches: [
            {
              id: 2801,
              name: "Black",
              isSelected: true,
              path: Scene5Category1Swatch1,
              thumbnailPath: Black,
              initialPosition: { x: 0, y: 0, z: 0 },
              initialRotation: { x: 0, y: -90, z: 0 },
            },
            {
              id: 2802,
              name: "Blue",
              isSelected: false,
              path: Scene5Category1Swatch2,
              thumbnailPath: Blue,
              initialPosition: { x: 0, y: 0, z: 0 },
              initialRotation: { x: 0, y: -90, z: 0 },
            },
            {
              id: 2803,
              name: "Red",
              isSelected: false,
              path: Scene5Category1Swatch3,
              thumbnailPath: Red,
              initialPosition: { x: 0, y: 0, z: 0 },
              initialRotation: { x: 0, y: -90, z: 0 },
            },
            {
              id: 2804,
              name: "White",
              isSelected: false,
              path: Scene5Category1Swatch4,
              thumbnailPath: White,
              initialPosition: { x: 0, y: 0, z: 0 },
              initialRotation: { x: 0, y: -90, z: 0 },
            },
          ],
        },
      ],
      hotspots: [
        {
          id: 1817,
          thumbnail: Hotspot,
          header: "Scene 1",
          sceneId: 4801,
          initialPosition: { x: 5, y: -2, z: -15 },
          initialRotation: { x: 0, y: 0, z: 0 },
        },
        {
          id: 1818,
          thumbnail: Hotspot,
          header: "Scene 2",
          sceneId: 4802,
          initialPosition: { x: 0, y: 1, z: -15 },
          initialRotation: { x: 0, y: 0, z: 0 },
        },
        {
          id: 1819,
          thumbnail: Hotspot,
          header: "Scene 3",
          sceneId: 4803,
          initialPosition: { x: 3, y: -0.5, z: -15 },
          initialRotation: { x: 0, y: 0, z: 0 },
        },
        {
          id: 1820,
          thumbnail: Hotspot,
          header: "Scene 4",
          sceneId: 4804,
          initialPosition: { x: 5, y: -7, z: -15 },
          initialRotation: { x: 0, y: 0, z: 0 },
        },
      ],
    },
    {
      id: 4806,
      name: "Opened_Door_Side",
      baseImage: Scene6BaseImage,
      initialPosition: { x: 0, y: 0, z: 0 },
      initialRotation: { x: 0, y: -90, z: 0 },
      isDefault: true,
      categories: [
        {
          id: 3801,
          name: "Color",
          thumbnail: ColorIcon,
          swatches: [
            {
              id: 2801,
              name: "Black",
              isSelected: true,
              path: Scene6Category1Swatch1,
              thumbnailPath: Black,
              initialPosition: { x: 0, y: 0, z: 0 },
              initialRotation: { x: 0, y: -90, z: 0 },
            },
            {
              id: 2802,
              name: "Blue",
              isSelected: false,
              path: Scene6Category1Swatch2,
              thumbnailPath: Blue,
              initialPosition: { x: 0, y: 0, z: 0 },
              initialRotation: { x: 0, y: -90, z: 0 },
            },
            {
              id: 2803,
              name: "Red",
              isSelected: false,
              path: Scene6Category1Swatch3,
              thumbnailPath: Red,
              initialPosition: { x: 0, y: 0, z: 0 },
              initialRotation: { x: 0, y: -90, z: 0 },
            },
            {
              id: 2804,
              name: "White",
              isSelected: false,
              path: Scene6Category1Swatch4,
              thumbnailPath: White,
              initialPosition: { x: 0, y: 0, z: 0 },
              initialRotation: { x: 0, y: -90, z: 0 },
            },
          ],
        },
        {
          id: 3802,
          name: "Alloys",
          thumbnail: WheelIcon,
          swatches: [
            {
              id: 2805,
              name: "Alloy 1",
              isSelected: true,
              path: Scene6Category2Swatch1,
              thumbnailPath: Alloy1,
              initialPosition: { x: 0, y: 0, z: 0 },
              initialRotation: { x: 0, y: -90, z: 0 },
            },
            {
              id: 2806,
              name: "Alloy 2",
              isSelected: false,
              path: Scene6Category2Swatch2,
              thumbnailPath: Alloy2,
              initialPosition: { x: 0, y: 0, z: 0 },
              initialRotation: { x: 0, y: -90, z: 0 },
            },
            {
              id: 2807,
              name: "Alloy 3",
              isSelected: false,
              path: Scene6Category2Swatch3,
              thumbnailPath: Alloy3,
              initialPosition: { x: 0, y: 0, z: 0 },
              initialRotation: { x: 0, y: -90, z: 0 },
            },
          ],
        },
      ],
      hotspots: [
        {
          id: 1821,
          thumbnail: Hotspot,
          header: "Scene 7",
          sceneId: 4807,
          initialPosition: { x: 10, y: 0, z: -15 },
          initialRotation: { x: 0, y: 0, z: 0 },
        },
        {
          id: 1822,
          thumbnail: Hotspot,
          header: "Scene 8",
          sceneId: 4808,
          initialPosition: { x: 17, y: -6, z: -15 },
          initialRotation: { x: 0, y: 0, z: 0 },
        },
        {
          id: 1823,
          thumbnail: Hotspot,
          header: "Scene 9",
          sceneId: 4809,
          initialPosition: { x: -14, y: -6, z: -15 },
          initialRotation: { x: 0, y: 0, z: 0 },
        },
        {
          id: 1824,
          thumbnail: Hotspot,
          header: "Scene 10",
          sceneId: 4810,
          initialPosition: { x: -14, y: -1, z: -15 },
          initialRotation: { x: 0, y: 0, z: 0 },
        },
      ],
    },
    {
      id: 4807,
      name: "Opened_Door_Front",
      baseImage: Scene7BaseImage,
      initialPosition: { x: 0, y: 0, z: 0 },
      initialRotation: { x: 0, y: -90, z: 0 },
      isDefault: false,
      categories: [
        {
          id: 3801,
          name: "Color",
          thumbnail: ColorIcon,
          swatches: [
            {
              id: 2801,
              name: "Black",
              isSelected: true,
              path: Scene7Category1Swatch1,
              thumbnailPath: Black,
              initialPosition: { x: 0, y: 0, z: 0 },
              initialRotation: { x: 0, y: -90, z: 0 },
            },
            {
              id: 2802,
              name: "Blue",
              isSelected: false,
              path: Scene7Category1Swatch2,
              thumbnailPath: Blue,
              initialPosition: { x: 0, y: 0, z: 0 },
              initialRotation: { x: 0, y: -90, z: 0 },
            },
            {
              id: 2803,
              name: "Red",
              isSelected: false,
              path: Scene7Category1Swatch3,
              thumbnailPath: Red,
              initialPosition: { x: 0, y: 0, z: 0 },
              initialRotation: { x: 0, y: -90, z: 0 },
            },
            {
              id: 2804,
              name: "White",
              isSelected: false,
              path: Scene7Category1Swatch4,
              thumbnailPath: White,
              initialPosition: { x: 0, y: 0, z: 0 },
              initialRotation: { x: 0, y: -90, z: 0 },
            },
          ],
        },
      ],
      hotspots: [
        {
          id: 1825,
          thumbnail: Hotspot,
          header: "Scene 6",
          sceneId: 4806,
          initialPosition: { x: -4, y: -1, z: -15 },
          initialRotation: { x: 0, y: 0, z: 0 },
        },
        {
          id: 1826,
          thumbnail: Hotspot,
          header: "Scene 8",
          sceneId: 4808,
          initialPosition: { x: -5, y: -8, z: -15 },
          initialRotation: { x: 0, y: 0, z: 0 },
        },
        {
          id: 1827,
          thumbnail: Hotspot,
          header: "Scene 9",
          sceneId: 4809,
          initialPosition: { x: 4, y: 0, z: -15 },
          initialRotation: { x: 0, y: 0, z: 0 },
        },
        {
          id: 1828,
          thumbnail: Hotspot,
          header: "Scene 10",
          sceneId: 4810,
          initialPosition: { x: 0.5, y: 1, z: -15 },
          initialRotation: { x: 0, y: 0, z: 0 },
        },
      ],
    },
    {
      id: 4808,
      name: "Opened_Door_Right",
      baseImage: Scene8BaseImage,
      initialPosition: { x: 0, y: 0, z: 0 },
      initialRotation: { x: 0, y: -90, z: 0 },
      isDefault: false,
      categories: [
        {
          id: 3801,
          name: "Color",
          thumbnail: ColorIcon,
          swatches: [
            {
              id: 2801,
              name: "Black",
              isSelected: true,
              path: Scene8Category1Swatch1,
              thumbnailPath: Black,
              initialPosition: { x: 0, y: 0, z: 0 },
              initialRotation: { x: 0, y: -90, z: 0 },
            },
            {
              id: 2802,
              name: "Blue",
              isSelected: false,
              path: Scene8Category1Swatch2,
              thumbnailPath: Blue,
              initialPosition: { x: 0, y: 0, z: 0 },
              initialRotation: { x: 0, y: -90, z: 0 },
            },
            {
              id: 2803,
              name: "Red",
              isSelected: false,
              path: Scene8Category1Swatch3,
              thumbnailPath: Red,
              initialPosition: { x: 0, y: 0, z: 0 },
              initialRotation: { x: 0, y: -90, z: 0 },
            },
            {
              id: 2804,
              name: "White",
              isSelected: false,
              path: Scene8Category1Swatch4,
              thumbnailPath: White,
              initialPosition: { x: 0, y: 0, z: 0 },
              initialRotation: { x: 0, y: -90, z: 0 },
            },
          ],
        },
        {
          id: 3802,
          name: "Alloys",
          thumbnail: WheelIcon,
          swatches: [
            {
              id: 2805,
              name: "Alloy 1",
              isSelected: true,
              path: Scene8Category2Swatch1,
              thumbnailPath: Alloy1,
              initialPosition: { x: 0, y: 0, z: 0 },
              initialRotation: { x: 0, y: -90, z: 0 },
            },
            {
              id: 2806,
              name: "Alloy 2",
              isSelected: false,
              path: Scene8Category2Swatch2,
              thumbnailPath: Alloy2,
              initialPosition: { x: 0, y: 0, z: 0 },
              initialRotation: { x: 0, y: -90, z: 0 },
            },
            {
              id: 2807,
              name: "Alloy 3",
              isSelected: false,
              path: Scene8Category2Swatch3,
              thumbnailPath: Alloy3,
              initialPosition: { x: 0, y: 0, z: 0 },
              initialRotation: { x: 0, y: -90, z: 0 },
            },
          ],
        },
      ],
      hotspots: [
        {
          id: 1829,
          thumbnail: Hotspot,
          header: "Scene 6",
          sceneId: 4806,
          initialPosition: { x: -8, y: -4, z: -15 },
          initialRotation: { x: 0, y: 0, z: 0 },
        },
        {
          id: 1830,
          thumbnail: Hotspot,
          header: "Scene 7",
          sceneId: 4807,
          initialPosition: { x: 4, y: -4, z: -15 },
          initialRotation: { x: 0, y: 0, z: 0 },
        },
        {
          id: 1831,
          thumbnail: Hotspot,
          header: "Scene 9",
          sceneId: 4809,
          initialPosition: { x: -10, y: -4, z: -15 },
          initialRotation: { x: 0, y: 0, z: 0 },
        },
        {
          id: 1832,
          thumbnail: Hotspot,
          header: "Scene 10",
          sceneId: 4810,
          initialPosition: { x: -8, y: 1, z: -15 },
          initialRotation: { x: 0, y: 0, z: 0 },
        },
      ],
    },
    {
      id: 4809,
      name: "Opened_Door_Left",
      baseImage: Scene9BaseImage,
      initialPosition: { x: 0, y: 0, z: 0 },
      initialRotation: { x: 0, y: -90, z: 0 },
      isDefault: false,
      categories: [
        {
          id: 3801,
          name: "Color",
          thumbnail: ColorIcon,
          swatches: [
            {
              id: 2801,
              name: "Black",
              isSelected: true,
              path: Scene9Category1Swatch1,
              thumbnailPath: Black,
              initialPosition: { x: 0, y: 0, z: 0 },
              initialRotation: { x: 0, y: -90, z: 0 },
            },
            {
              id: 2802,
              name: "Blue",
              isSelected: false,
              path: Scene9Category1Swatch2,
              thumbnailPath: Blue,
              initialPosition: { x: 0, y: 0, z: 0 },
              initialRotation: { x: 0, y: -90, z: 0 },
            },
            {
              id: 2803,
              name: "Red",
              isSelected: false,
              path: Scene9Category1Swatch3,
              thumbnailPath: Red,
              initialPosition: { x: 0, y: 0, z: 0 },
              initialRotation: { x: 0, y: -90, z: 0 },
            },
            {
              id: 2804,
              name: "White",
              isSelected: false,
              path: Scene9Category1Swatch4,
              thumbnailPath: White,
              initialPosition: { x: 0, y: 0, z: 0 },
              initialRotation: { x: 0, y: -90, z: 0 },
            },
          ],
        },
        {
          id: 3802,
          name: "Alloys",
          thumbnail: WheelIcon,
          swatches: [
            {
              id: 2805,
              name: "Alloy 1",
              isSelected: true,
              path: Scene9Category2Swatch1,
              thumbnailPath: Alloy1,
              initialPosition: { x: 0, y: 0, z: 0 },
              initialRotation: { x: 0, y: -90, z: 0 },
            },
            {
              id: 2806,
              name: "Alloy 2",
              isSelected: false,
              path: Scene9Category2Swatch2,
              thumbnailPath: Alloy2,
              initialPosition: { x: 0, y: 0, z: 0 },
              initialRotation: { x: 0, y: -90, z: 0 },
            },
            {
              id: 2807,
              name: "Alloy 3",
              isSelected: false,
              path: Scene9Category2Swatch3,
              thumbnailPath: Alloy3,
              initialPosition: { x: 0, y: 0, z: 0 },
              initialRotation: { x: 0, y: -90, z: 0 },
            },
          ],
        },
      ],
      hotspots: [
        {
          id: 1833,
          thumbnail: Hotspot,
          header: "Scene 6",
          sceneId: 4806,
          initialPosition: { x: 9, y: -4, z: -15 },
          initialRotation: { x: 0, y: 0, z: 0 },
        },
        {
          id: 1834,
          thumbnail: Hotspot,
          header: "Scene 7",
          sceneId: 4807,
          initialPosition: { x: 10, y: 0, z: -15 },
          initialRotation: { x: 0, y: 0, z: 0 },
        },
        {
          id: 1835,
          thumbnail: Hotspot,
          header: "Scene 8",
          sceneId: 4808,
          initialPosition: { x: 11, y: -3, z: -15 },
          initialRotation: { x: 0, y: 0, z: 0 },
        },
        {
          id: 1836,
          thumbnail: Hotspot,
          header: "Scene 10",
          sceneId: 4810,
          initialPosition: { x: -1, y: -5, z: -15 },
          initialRotation: { x: 0, y: 0, z: 0 },
        },
      ],
    },
    {
      id: 4810,
      name: "Opened_Door_Back",
      baseImage: Scene10BaseImage,
      initialPosition: { x: 0, y: 0, z: 0 },
      initialRotation: { x: 0, y: -90, z: 0 },
      isDefault: false,
      categories: [
        {
          id: 3801,
          name: "Color",
          thumbnail: ColorIcon,
          swatches: [
            {
              id: 2801,
              name: "Black",
              isSelected: true,
              path: Scene10Category1Swatch1,
              thumbnailPath: Black,
              initialPosition: { x: 0, y: 0, z: 0 },
              initialRotation: { x: 0, y: -90, z: 0 },
            },
            {
              id: 2802,
              name: "Blue",
              isSelected: false,
              path: Scene10Category1Swatch2,
              thumbnailPath: Blue,
              initialPosition: { x: 0, y: 0, z: 0 },
              initialRotation: { x: 0, y: -90, z: 0 },
            },
            {
              id: 2803,
              name: "Red",
              isSelected: false,
              path: Scene10Category1Swatch3,
              thumbnailPath: Red,
              initialPosition: { x: 0, y: 0, z: 0 },
              initialRotation: { x: 0, y: -90, z: 0 },
            },
            {
              id: 2804,
              name: "White",
              isSelected: false,
              path: Scene10Category1Swatch4,
              thumbnailPath: White,
              initialPosition: { x: 0, y: 0, z: 0 },
              initialRotation: { x: 0, y: -90, z: 0 },
            },
          ],
        },
      ],
      hotspots: [
        {
          id: 1837,
          thumbnail: Hotspot,
          header: "Scene 6",
          sceneId: 4806,
          initialPosition: { x: 5, y: -2, z: -15 },
          initialRotation: { x: 0, y: 0, z: 0 },
        },
        {
          id: 1838,
          thumbnail: Hotspot,
          header: "Scene 7",
          sceneId: 4807,
          initialPosition: { x: 0, y: 1, z: -15 },
          initialRotation: { x: 0, y: 0, z: 0 },
        },
        {
          id: 1839,
          thumbnail: Hotspot,
          header: "Scene 8",
          sceneId: 4808,
          initialPosition: { x: 3, y: -0.5, z: -15 },
          initialRotation: { x: 0, y: 0, z: 0 },
        },
        {
          id: 1840,
          thumbnail: Hotspot,
          header: "Scene 9",
          sceneId: 4809,
          initialPosition: { x: 5, y: -7, z: -15 },
          initialRotation: { x: 0, y: 0, z: 0 },
        },
      ],
    },
  ],
};
